"use strict";
exports.__esModule = true;
var easyCalc_1 = require("./easyCalc");
var virtualCalc_1 = require("./virtualCalc");
var argum = 27;
var myCalc1 = new easyCalc_1.EasyCalc(argum);
console.log('\nInicialización de la calculadora con el argumento:', argum);
virtualCalc_1.VirtualCalc.print(myCalc1);
var myCalc = new easyCalc_1.EasyCalc();
console.log('\nInicialización de la calculadora sin argumento.');
virtualCalc_1.VirtualCalc.print(myCalc);
var suma = [2, 3, 5, 7, 11, 13, 17, 19, 23];
console.log('\nSumar:', suma);
myCalc.suma(suma);
virtualCalc_1.VirtualCalc.print(myCalc);
console.log('\nSumar sin parametros.');
myCalc.suma();
virtualCalc_1.VirtualCalc.print(myCalc);
var resta = [100, 41, 22, 15, 9, 4];
console.log('\nRestar:', resta);
myCalc.resta(resta);
virtualCalc_1.VirtualCalc.print(myCalc);
var mult = [5, 3, 20, 5, 9, 2];
console.log('\nMultiplicar:', mult);
myCalc.multiplicacion(mult);
virtualCalc_1.VirtualCalc.print(myCalc);
var div = [27000, 2, 9, 5, 20, 3];
console.log('\nDividir:', div);
myCalc.division(div);
virtualCalc_1.VirtualCalc.print(myCalc);
var num = 2022;
console.log('\nForzar el resultado a:', num);
myCalc.setResult(num);
virtualCalc_1.VirtualCalc.print(myCalc);
console.log('\nReset de la calculadora.');
myCalc.reset();
virtualCalc_1.VirtualCalc.print(myCalc);
console.log('Resultados de los métodos \'static\'.');
console.log('Sumar:', easyCalc_1.EasyCalc.suma(suma));
console.log('Restar:', easyCalc_1.EasyCalc.resta(resta));
console.log('Multiplicar:', easyCalc_1.EasyCalc.multiplicacion(mult));
console.log('Dividir:', easyCalc_1.EasyCalc.division(div));
